version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes: 
      - ./data:/data/db
    ports: 
      - "270017":"27017"
  api:
    container_name: api-container
    build: .
    image: tdd-node-api
    restart: always
    command: npm start
    volumes:
    -./dist:/usr/workspace/tdd-node-api/dist
    ports: 
      - "5050:5050"
    links:
    - mongo